### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by WesselSmit** [kriskuiper/web-app-from-scratch-1920#11]
https://github.com/kriskuiper/web-app-from-scratch-1920/blob/914196ec080e0259a85fa7685144c07b9e126a13/src/router/index.js#L41-L55

Function names zoals `push` en `replace` geven aan dat er iets `gepushed` of `gereplaced` word, maar ze geven niet duidelijk aan wat er `gepushed` of `gereplaced`. Overweeg om iets meer omschrijvende names te gebruiken die duidelijker aangeven OP WAT het gebeurt.

**Comment by kriskuiper** [comment]
Ik snap je punt maar `push` en `replace` is een soort standaardisatie binnen routers. Als je vue router gebruikt doe je bijvoorbeeld ook `this.$router.push()` etc. Dus in mijn router ook.

**Comment by iamDistractech** [comment]
Je kan ook comments(JSdoc) gebruiken om aan te geven wat er gebeurt

**Comment by joostf** [comment]
Lekker bezig, jongens!

**Comment by kriskuiper** [comment]
@iSirThijs denk inderdaad dat ik dat ga doen bij vrijwel elk ding
