### ISSUE TITLE
Shorter name here?

### ISSUE THREAD

**Issue by joostf** [kriskuiper/web-app-from-scratch-1920#13]
https://github.com/kriskuiper/web-app-from-scratch-1920/blob/914196ec080e0259a85fa7685144c07b9e126a13/src/router/index.js#L57

Your already in `router` so why not call the method `updateView`?

**Comment by kriskuiper** [comment]
True that, will implement this 👍

**Comment by joostf** [comment]
Same here?

https://github.com/kriskuiper/web-app-from-scratch-1920/blob/914196ec080e0259a85fa7685144c07b9e126a13/src/lib/format-date.js#L1

`prefix` would be clear here?

**Comment by kriskuiper** [comment]
Yeah, you'd read it like 'prefix num' etc. So... true
