### ISSUE TITLE
Inner html

### ISSUE THREAD

**Issue by LarsBreuren** [kriskuiper/web-app-from-scratch-1920#26]
https://github.com/kriskuiper/web-app-from-scratch-1920/blob/0938487c9d8084f15a03aacd069d6b345229c88b/docs/js/main.js#L50

You might want to check out this innerHTML, there might be better and/or safer solutions to update the HTML elements.

**Comment by Mennauu** [comment]
FYI: https://stackoverflow.com/a/16127063/1300427

**Comment by kriskuiper** [comment]
Thanks! Was thinking about writing some simple functions to abstract the logic of appendChild, removeChild etc. so will definately implement this 👍

**Comment by kriskuiper** [comment]
Fixed it by using [Redom](https://redom.js.org/) as template engine
