### ISSUE TITLE
Assessment 

### ISSUE THREAD

**Issue by MohamadAlGhorani** [kriskuiper/web-app-from-scratch-1920#29]
1- Je code is redelijk netjes maar je kunt hier en daar wat meer consistent zijn in notatiewijze / structuur
2- Je hebt zelf onderzoek gedaan en bent diep in materie gedoken. Er zijn bewuste keuzes gemaakt in de code structuur die verdedigd kunnen worden.
3- Je hebt met een promise asynchroon data opgehaald uit een API
4- Je kan de methodes map, filter en reduce toepassen om JSON data te manipuleren en je kan uitleggen hoe deze methodes werken
5- Het is gelukt om, met behulp van een micro library, JSON data te renderen naar HTML
6- Je hebt je eigen router geschreven
7- De flow is dusdanig gevisualiseerd dat code en interactie van de app redelijk te begrijpen zijn
8- Voeg een paar states aan je applicatie zoals loading state en error state zodat de gebruiker goed feedback krijgt tijdens het gebruiken van je app.

Verder is het helemaal goed keep it up man en probeer je data te renderen  op de site zodat we mooie dingen kunnen zien.😁

**Comment by kriskuiper** [comment]
Cool! Handling your tips in #31
