### ISSUE TITLE
.gitignore content

### ISSUE THREAD

**Issue by WesselSmit** [kriskuiper/web-app-from-scratch-1920#3]
Ik zou files zoals: 
- .editorconfig
- .gitignore
- .package.json
- .rollup.config.js
- yarn.lock

in de .gitignore zetten, dit maakt de repo wat overzichtelijker

**Comment by kriskuiper** [comment]
Geen van de bovenstaande files hoeft in de .gitignore aangezien iedereen die aan dit project zou werken ze nodig heeft 😅
