### ISSUE TITLE
Add 'data' to readme

### ISSUE THREAD

**Issue by WesselSmit** [kriskuiper/web-app-from-scratch-1920#5]
De API section in de readme is nog niet af, overweeg om de volgende dingen in de README te verwerken:
- Overview --> geef aan wat voor content je krijgt 
- Endpoints --> leg uit wat voor data je krijgt over de launches
- API limitations --> rate limit

verder zou ik nog de volgende dingen toevoegen:
- Key --> moet je een key hebben?
- Data --> hoe ziet de data eruit die je ontvangt, wat doe je ermee (opschonen, transformeren, lege waardes)?

**Comment by kriskuiper** [comment]
What does the data look like that comes out of the API, what do I do to clean that?
